### PR TITLE
Custom parent selector

### PR DESCRIPTION
**Pull request by AntJanus**
This is pretty useful for forced clean up. The toolbar for an editing field gets appended to the body so that when you switch views, it gets orphaned. A new toolbar is made every time an editor is invoked so this can quickly add up. Editing a bunch of posts in a CMS can easily yield 20-30 toolbar instances.

Anyways, a custom parent container can easily be used to specify a `ui-view` or `ng-view` selector so that whenever the user switches views, the toolbar instances get destroyed (Yay!).

edit: also, `querySelector` has IE9+ support, same as Angular. And if the selector can't find the element (or there is no selector), it attaches to the document body as before.

### CODE REVIEW

**Comment by ghinda** [comment]
Looks good overall. Just two things.

* Can you make the changes in the `app/scripts/directives/editor.js` file, then run `grunt build`?
This will automatically generate the everything in the `/dist` folder. You shouldn't edit anything from the `/dist` folder directly.

To be able to run the Grunt task, you'll have to have Node.js with npm installed, then run:

```
npm install -g grunt-cli
npm install
```

in the project root folder (where the `Gruntfile.js` is).

While working on the directive, you can run `grunt server`. This will start a local server with livereload at `http://localhost:9000/`.

* Can you change the `parentContainer` property to `toolbarContainer`, just to make it more clear?

Thanks!

**Comment by AntJanus** [comment]
Will do! :)

**Comment by ghinda** [comment]
Don't know how I missed your pull request for this long. Sorry for the delay!

Merged and released as `1.4.1`. :shipit:  Great work!

**Comment by AntJanus** [comment]
No problem! I've been using my fork for the time being.

Thanks for merging it in! :)

**Pull request merged**
